### PR TITLE
Issue 91: CHANGELOG.rst: Update for initial release

### PR DESCRIPTION
**Pull request by sjlongland**
Release 0.1.0 is imminent now.

Closes issue #91.

### CODE REVIEW

**Comment by sjlongland** [comment]
… let me fix that bad spelling. :-)

**Comment by diazona** [comment]
Since I'm pretty tired let me come back to review this tomorrow, if you don't mind.

**Comment by diazona** [comment]
What do you think about adding extra changelog entries for all the features that came before? Basically I'm thinking that we just go back and create a quick changelog fragment for each notable issue that was solved in getting up to this point - it'll be easy enough to get a list of the issues and should be no problem to pick out the notable ones - and then run `towncrier` with all those changelog fragments in place so it comes out as if we've been maintaining the changelog all along. (Not that anyone will be fooled, the Git history shows what happened; it's more about just documenting the progress up to this point. I'm thinking if we're going to have a changelog we might as well be somewhat thorough about it.)

**Comment by sjlongland** [comment]
Yep… might be able to pull out a list of the issues fixed through the Github APIs to dump the material out.

**Comment by sjlongland** [comment]
Fumbled my way through it…

```graphql
# Type queries here, and you will see intelligent autosuggestions
# aware of GitHub's current GraphQL schema, equipped with live
# syntax and validation errors highlighted within the text. We'll
# get you started with a simple query showing your username!

query {
  repository(owner:"diazona", name:"setuptools-pyproject-migration") {
    issues(states:CLOSED, first:100) {
      nodes {
        number
        title
        labels(first:10) {
          nodes {
            name
          }
        }
      }
    }
  }
}
```

```json
{
  "data": {
    "repository": {
      "issues": {
        "nodes": [
          {
            "number": 9,
            "title": "Update development status to 3",
            "labels": {
              "nodes": []
            }
          },
          {
            "number": 10,
            "title": "Add Stuart as a collaborator on PyPI",
            "labels": {
              "nodes": []
            }
          },
          {
            "number": 18,
            "title": "Set up documentation on ReadTheDocs",
            "labels": {
              "nodes": [
                {
                  "name": "documentation"
                }
              ]
            }
          },
          {
            "number": 19,
            "title": "Add Stuart as a collaborator on ReadTheDocs",
            "labels": {
              "nodes": []
            }
          },
          {
            "number": 20,
            "title": "Rewrite release logic",
            "labels": {
              "nodes": []
            }
          },
          {
            "number": 28,
            "title": "Support authors and maintainers",
            "labels": {
              "nodes": [
                {
                  "name": "enhancement"
                },
                {
                  "name": "good first issue"
                },
                {
                  "name": "setuptools-fields"
                }
              ]
            }
          },
          {
            "number": 29,
            "title": "Support classifiers",
            "labels": {
              "nodes": [
                {
                  "name": "enhancement"
                },
                {
                  "name": "good first issue"
                },
                {
                  "name": "setuptools-fields"
                }
              ]
            }
          },
          {
            "number": 30,
            "title": "Support description",
            "labels": {
              "nodes": [
                {
                  "name": "enhancement"
                },
                {
                  "name": "good first issue"
                },
                {
                  "name": "setuptools-fields"
                }
              ]
            }
          },
          {
            "number": 31,
            "title": "Support keywords",
            "labels": {
              "nodes": [
                {
                  "name": "enhancement"
                },
                {
                  "name": "good first issue"
                },
                {
                  "name": "setuptools-fields"
                }
              ]
            }
          },
          {
            "number": 32,
            "title": "Support license",
            "labels": {
              "nodes": [
                {
                  "name": "enhancement"
                },
                {
                  "name": "good first issue"
                },
                {
                  "name": "setuptools-fields"
                }
              ]
            }
          },
          {
            "number": 33,
            "title": "Support readme",
            "labels": {
              "nodes": [
                {
                  "name": "enhancement"
                },
                {
                  "name": "good first issue"
                },
                {
                  "name": "setuptools-fields"
                }
              ]
            }
          },
          {
            "number": 34,
            "title": "Support requires-python",
            "labels": {
              "nodes": [
                {
                  "name": "enhancement"
                },
                {
                  "name": "good first issue"
                },
                {
                  "name": "setuptools-fields"
                }
              ]
            }
          },
          {
            "number": 35,
            "title": "Support urls",
            "labels": {
              "nodes": [
                {
                  "name": "enhancement"
                },
                {
                  "name": "good first issue"
                },
                {
                  "name": "setuptools-fields"
                }
              ]
            }
          },
          {
            "number": 36,
            "title": "Support entry points",
            "labels": {
              "nodes": [
                {
                  "name": "enhancement"
                },
                {
                  "name": "good first issue"
                },
                {
                  "name": "setuptools-fields"
                }
              ]
            }
          },
          {
            "number": 37,
            "title": "Support extras",
            "labels": {
              "nodes": [
                {
                  "name": "enhancement"
                },
                {
                  "name": "good first issue"
                },
                {
                  "name": "setuptools-fields"
                }
              ]
            }
          },
          {
            "number": 38,
            "title": "Enable pre-commit.ci",
            "labels": {
              "nodes": []
            }
          },
          {
            "number": 39,
            "title": "Separate static checks from pytest",
            "labels": {
              "nodes": [
                {
                  "name": "bug"
                }
              ]
            }
          },
          {
            "number": 43,
            "title": "Configure trusted publishing",
            "labels": {
              "nodes": []
            }
          },
          {
            "number": 61,
            "title": "Remove maximum setuptools version once the circular import issue is resolved",
            "labels": {
              "nodes": []
            }
          },
          {
            "number": 71,
            "title": "Write some meaningful documentation",
            "labels": {
              "nodes": [
                {
                  "name": "documentation"
                }
              ]
            }
          },
          {
            "number": 86,
            "title": "Slow tests do not run from manually triggered workflows",
            "labels": {
              "nodes": []
            }
          },
          {
            "number": 88,
            "title": "Enable towncrier",
            "labels": {
              "nodes": [
                {
                  "name": "documentation"
                }
              ]
            }
          }
        ]
      }
    }
  }
}
```
```

**Comment by sjlongland** [comment]
```
RC=0 stuartl@rikishi ~/projects/setuptools-pyproject-migration/work $ ipython3
Python 3.11.5 (main, Aug 27 2023, 13:49:13) [GCC 12.3.1 20230526]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.12.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import os, json

In [2]: issues = json.loads(open("/tmp/issues.json","r").read())['data']['repository']['issues']['nodes']

In [3]: for i in issues:
   ...:     labels = set(l['name'] for l in i['labels']['nodes'])
   ...:     if 'enhancement' in labels:
   ...:         t='feature'
   ...:     elif 'documentation' in labels:
   ...:         t='doc'
   ...:     else:
   ...:         t='fixed'
   ...:     fn = 'changelog.d/%d.%s' % (i['number'], t)
   ...:     if os.path.isfile(fn):
   ...:         continue
   ...:     with open(fn, "w") as f:
   ...:         f.write(i['title'])
   ...: 
```

I deleted some trivial issues like #10… but that brought everything across.

**Review by diazona — APPROVED** [review]
Ah sure, this works. (I was also thinking it'd be within the scope of doing manually, but it's all good.)

**Pull request merged**
